services:
  myapp:
    environment:
      XDG_DATA_HOME: /data
      XDG_STATE_HOME: /state
      XDG_CACHE_HOME: /cache
      XDG_CONFIG_HOME: /config

    volumes:
      - ./_runtime/data:/data
      - ./_runtime/state:/state
      - ./_runtime/cache:/cache
      - ./config:/config:ro


